version: "3.3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 5050:5050
    environment:
      - ENV=development
      - MONGODB_HOST=database
      - MONGODB_USER=root
      - MONGODB_PASSWORD=secret
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=keeper
    restart: always

  test-database:
    image: mongo
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=keeper-test
    restart: always

  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    restart: always

  redis-commander:
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8082:8081
    depends_on:
      - redis

  client:
    build:
      context: .
      dockerfile: Dockerfile.client.dev
    ports:
      - 3000:3000
    environment:
      - VITE_BACKEND_URL=http://localhost:5050
    volumes:
      - ./client/:/app
    depends_on:
      - backend
      - database
