FROM golang:1.16-alpine AS builder 
RUN mkdir /app 
COPY . /app 
WORKDIR /app 
RUN printenv
# install dependencies
# RUN go mod download 
RUN go mod vendor
# generate the executable 
RUN go build -o bin/main cmd/server.go

# for the multi-stage build
FROM alpine  
WORKDIR /app 
COPY --from=builder /app /app/

# # Add bash 
RUN apk add --no-cache bash

EXPOSE $PORT

CMD ["/app/bin/main"]