version: "3.3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports: 
      - 5050:5050
    environment: 
      - ENV=development 
      - MONGODB_HOST=database 
      - MONGODB_USER=root 
      - MONGODB_PASSWORD=secret

  database:
    image: mongo  
    ports:
      - 27017:27017 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret 
      - MONGO_INITDB_DATABASE=keeper
    restart: always 


  client:
    build:
      context: .
      dockerfile: Dockerfile.client
